### ISSUE TITLE
document.mGet does not provide the _source

### ISSUE THREAD

**Issue by dbengsch** [kuzzleio/kuzzle#999] opened 2017-11-27 20:30 UTC
The `document.mGet` method does not provide the _source in the response.

**Comment by benoitvidis** [comment] 2017-12-04 15:45
@dbengsch , I am sorry, I cannot reproduce the issue:

```
> {"controller": "document", "action": "mGet", "index": "index", "collection": "collection", "body": {"ids": ["AWAiKMmZunrQp3rur8qp", "AWAiKOY5unrQp3rur8qq"]}}
< {"requestId":"1b9a4190-6427-4c78-8771-3db7ec677182","status":200,"error":null,"controller":"document","action":"mGet","collection":"collection","index":"index","volatile":null,"result":{"hits":[{"_index":"index","_type":"collection","_id":"AWAiKMmZunrQp3rur8qp","_version":1,"found":true,"_source":{"foo":"bar"},"_meta":{"author":"-1","createdAt":1512401586582,"updatedAt":null,"updater":null,"active":true,"deletedAt":null}},{"_index":"index","_type":"collection","_id":"AWAiKOY5unrQp3rur8qq","_version":1,"found":true,"_source":{"foo":"baz"},"_meta":{"author":"-1","createdAt":1512401593911,"updatedAt":null,"updater":null,"active":true,"deletedAt":null}}],"total":2},"room":"1b9a4190-6427-4c78-8771-3db7ec677182"}
```
in http:

```
curl -H "Content-type: application/json" -d '{"ids": ["AWAiKMmZunrQp3rur8qp", "AWAiKOY5unrQp3rur8qq"]}' "http://localhost:7512/index/collection/_mGet?pretty"

{
  "requestId": "a115a91b-ea1c-4f11-9ac6-89af53853347",
  "status": 200,
  "error": null,
  "controller": "document",
  "action": "mGet",
  "collection": "collection",
  "index": "index",
  "volatile": null,
  "result": {
    "hits": [
      {
        "_index": "index",
        "_type": "collection",
        "_id": "AWAiKMmZunrQp3rur8qp",
        "_version": 1,
        "found": true,
        "_source": {
          "foo": "bar"
        },
        "_meta": {
          "author": "-1",
          "createdAt": 1512401586582,
          "updatedAt": null,
          "updater": null,
          "active": true,
          "deletedAt": null
        }
      },
      {
        "_index": "index",
        "_type": "collection",
        "_id": "AWAiKOY5unrQp3rur8qq",
        "_version": 1,
        "found": true,
        "_source": {
          "foo": "baz"
        },
        "_meta": {
          "author": "-1",
          "createdAt": 1512401593911,
          "updatedAt": null,
          "updater": null,
          "active": true,
          "deletedAt": null
        }
      }
    ],
    "total": 2
  }
}
```

**Comment by benoitvidis** [comment] 2017-12-04 16:22
After discussion, closing the issue as we are not able to reproduce it.

**Closed by benoitvidis** 2017-12-04 16:22 UTC
Labels: bug, priority-normal
