### ISSUE TITLE
deleteByQuery on invalid index/collections result in a dump...

### ISSUE THREAD

**Issue by etrousset** [kuzzleio/kuzzle#992] opened 2017-11-10 15:49 UTC
Trying to delete a index / collection that doesn't existe resulted in a core dump

dump_no-such-index.zip available on my hard drive if needed

**Comment by etrousset** [comment] 2017-11-10 15:50
Logs:

kuzzle_1         | ::ffff:192.168.1.106 - - [10/Nov/2017:15:32:15 +0000] "DELETE /index/collection1/_query HTTP/1.1" 500 2318 - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36"
kuzzle_1         | ===========================================================================
kuzzle_1         | Generating dump in dump/20171110-153215-handled-internalerror-index_not_found_exception-no-such-index-with-resource-type-index_or_alias-resource-id-index-index_uuid-_na_-index-index
kuzzle_1         | > dumping kuzzle configuration
kuzzle_1         | > dumping plugins configuration
kuzzle_1         | > dumping nodejs configuration
kuzzle_1         | > dumping os configuration
kuzzle_1         | > dumping std err/out
kuzzle_1         | 2017-11-10T15:32:15+00:00 [LOG:ERROR] (500) [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="index" & index_uuid="_na_" & index="index" }
kuzzle_1         | [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="index" & index_uuid="_na_" & index="index" } :: {"path":"/index/collection1/_search","query":{"scroll":"30s"},"body":"{\"query\":{\"bool\":{\"filter\":{\"bool\":{\"must_not\":{\"term\":{\"_kuzzle_info.active\":false}}}},\"must\":{}}}}","statusCode":404,"response":"{\"error\":{\"root_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"index\",\"index_uuid\":\"_na_\",\"index\":\"index\"}],\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"index\",\"index_uuid\":\"_na_\",\"index\":\"index\"},\"status\":404}"}
kuzzle_1         |     at respond (/var/app/node_modules/elasticsearch/src/lib/transport.js:307:15)
kuzzle_1         |     at checkRespForFailure (/var/app/node_modules/elasticsearch/src/lib/transport.js:266:7)
kuzzle_1         |     at HttpConnector.<anonymous> (/var/app/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)
kuzzle_1         |     at IncomingMessage.bound (/var/app/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
kuzzle_1         |     at emitNone (events.js:91:20)
kuzzle_1         |     at IncomingMessage.emit (events.js:185:7)
kuzzle_1         |     at endReadableNT (_stream_readable.js:974:12)
kuzzle_1         |     at _combinedTickCallback (internal/process/next_tick.js:80:11)
kuzzle_1         |     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
elasticsearch_1  | [2017-11-10T15:32:30,831][WARN ][o.e.d.i.q.QueryParseContext] query malformed, empty clause found at [1:97]
elasticsearch_1  | [2017-11-10T15:32:33,059][WARN ][o.e.d.i.q.QueryParseContext] query malformed, empty clause found at [1:97]
kuzzle_1         | > generating core-dump
kuzzle_1         | [dumpme] [New LWP 110]
kuzzle_1         | [dumpme] [New LWP 109]
kuzzle_1         | [dumpme] [New LWP 108]
kuzzle_1         | [dumpme] [New LWP 107]
kuzzle_1         | [dumpme] [New LWP 106]
kuzzle_1         | [dumpme] [New LWP 105]
kuzzle_1         | [dumpme] [New LWP 104]
kuzzle_1         | [dumpme] [New LWP 103]
kuzzle_1         | [dumpme] [New LWP 102]
kuzzle_1         | [dumpme] [Thread debugging using libthread_db enabled]
kuzzle_1         | [dumpme] Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
kuzzle_1         | [dumpme] 0x00007f2d11649bbd in read () at ../sysdeps/unix/syscall-template.S:81
kuzzle_1         | [dumpme] 81	../sysdeps/unix/syscall-template.S: No such file or directory.
kuzzle_1         | [dumpme] warning: Memory read failed for corefile section, 8192 bytes at 0x7ffc99fb3000.
kuzzle_1         | [dumpme] Saved corefile dump/20171110-153215-handled-internalerror-index_not_found_exception-no-such-index-with-resource-type-index_or_alias-resource-id-index-index_uuid-_na_-index-index/core.101
kuzzle_1         | > copy node binary
kuzzle_1         | > dumping kuzzle's stats
kuzzle_1         | Done.
kuzzle_1         | [ℹ] You can send the folder to the kuzzle core team at support@kuzzle.io
kuzzle_1         | ===========================================================================
elasticsearch_1  | [2017-11-10T15:34:30,841][WARN ][o.e.d.i.q.QueryParseContext] query malformed, empty clause found at [1:97]
elasticsearch_1  | [2017-11-10T15:34:38,052][WARN ][o.e.d.i.q.QueryParseContext] query malformed, empty clause found at [1:97]
redis_1          | 1:M 10 Nov 15:36:19.500 * 100 changes in 300 seconds. Saving...

**Comment by benoitvidis** [comment] 2018-08-06 14:30
Cannot reproduce anymore:

```
curl -XPOST http://localhost:7512/index/_create
curl -H 'content-type: application/json' -XDELETE -d '{"query": {}}' http://localhost:7512/index/idontexist/_query
{"requestId":"9d868a91-9869-407f-bb9a-d09fd97cd2ba","status":200,"error":null,"controller":"document","action":"deleteByQuery","collection":"idontexist","index":"index","volatile":null,"result":{"ids":[]}}%
```
@etrousset , can we close the issue?

**Comment by Aschen** [comment] 2019-11-28 12:09
Fixed in v2

**Closed by Aschen** 2019-11-28 12:09 UTC
Labels: acknowledged, bug
