### ISSUE TITLE
no 'deleteIndex' in SDK?

### ISSUE THREAD

**Issue by Tyki** [kuzzleio/kuzzle#1028] opened 2018-01-21 18:58 UTC
Hi,

Is it normal that there is no possibility to delete an index using the JS SDK?
There is only API option in the documentation.

**Comment by scottinet** [comment] 2018-01-22 15:40
This issue belongs to the [kuzzle-sdk](https://github.com/kuzzleio/kuzzle-sdk) repository.

And it is a duplicate of the following issue: https://github.com/kuzzleio/kuzzle-sdk/issues/51

**Closed by scottinet** 2018-01-22 15:40 UTC

**Comment by Tyki** [comment] 2018-01-22 17:04
Didn't saw the meta repository since there is nothing inside else I would have post the question there. 

Thanks for the workaround
