### ISSUE TITLE
Allow global wildcards in the router

### ISSUE THREAD

**Issue by benoitvidis** [kuzzleio/kuzzle#660] opened 2017-02-06 14:32 UTC
We may want in some situations to be able to define routes like

```
{verb: 'get', url: '/path/:param1/*param2*', controller: 'myController', action: 'action'}
```

Where param2 is catching the rest of the url, i.e.: 

* `_plugin/myPlugin/path/foo/bar` => param2 = bar
* `_plugin/myPlugin/path/foo/bar/some/other/params` => param2 = bar/some/other/params

**Comment by ballinette** [comment] 2017-08-22 10:28
2 options to benchmark:
* modify the actual HTTP routePart handler to add this behavious
* replace it by a regexp management.

**Comment by scottinet** [comment] 2017-09-22 09:53
I'm against using regular expressions in the HTTP router, for the following reasons:

* it's slow: there is no way to preemptively discard routes based upon regular expressions, they need to all be tested individually
* introducing regular expressions will make the router dependant on the order of the routes declared, as it was when we used the express router. This makes the handling of large number or routes clunky, and introduces side-effect like unrelated routes being invoked because their regular expressions are too greedy and declared before more specialized routes
* this will disable the route-checking feature, ensuring that there are no route duplicate. When using regular expressions it is impossible to make sure that all defined routes are unique

In a nutshell: this would defeat our custom HTTP router purpose and we might as-well go back to using the express one. And I do think that our router is better than the express one by a loooooong shot.

But @benoitvidis' proposal would also introduce a nice feature: being able to declare all-purpose HTTP routes, and this may have its uses.

I propose the following solution: introduce a generic `*` wildcard term, that can be only defined at the end of a URL definition.
This would be presented like this:

```
{verb: 'get', url: '/path/:param1/*', controller: 'myController', action: 'action'}
```

With the following behaviors:

* the URL `/path/foobar` will NOT be matched by this route (the wildcard would require that at least 1 parameter is defined)
* the router will refuse to register any other route with more precise parameters. For instance, the following route will make the router throw with a "duplicate route" error: `{verb: 'get', url: '/path/:param1/:param2', controller: 'myController', action: 'action'}`. Because doing so will make it impossible for the router to chose between the wildcard route and the more precise one

That way, we can create "black hole" HTTP routes without resorting to regular expressions. The changes in the router would also be minimal, as a wildcard would only act as a "stop" when building the routes tree.

What do you think?

(/poke @ballinette, @benoitvidis)

**Comment by benoitvidis** [comment] 2017-10-10 15:17
Following our discussion, I propose to accept both the wildcard &/or static and parametric args, the rule being: the more specific superseeds the less specific

i.e: /foo/bar => will match /foo/bar over /foo/:param over /foo/*wildcard

Other notes:

* wildcards match an empty path (/foo matches /foo/*wildcard).
* We can define default `OPTIONS` & `HEAD` routes as wildcards

**Comment by scottinet** [comment] 2017-10-10 15:21
As discussed, I agree with all that. :+1: 

I'll simply amend the duplicate rule: a more specific route will not be considered as a duplicate of a wildcard route, but two same wildcard routes must be considered as duplicates

**Comment by ballinette** [comment] 2018-03-01 18:44
Issue moved to [kuzzleio/kuzzle-backlog #119](https://github.com/kuzzleio/kuzzle-backlog/issues/119) via [**ZenHub**](https://www.zenhub.com/)

**Closed by ballinette** 2018-03-01 18:44 UTC
Labels: enhancement, priority-normal
