### ISSUE TITLE
Can't run Kuzzle with Docker-Compose on a fresh install

### ISSUE THREAD

**Issue by tsauvajon** [kuzzleio/kuzzle#1696] opened 2020-06-29 01:11 UTC
Running Kuzzle with Docker-Compose fails if `node_modules` are not present.

## Expected Behavior
When cloning the repository in a new environment and running `docker-compose up`, Kuzzle should start.

## Current Behavior

In https://github.com/kuzzleio/kuzzle/blob/master/docker/scripts/run-dev.sh#L15:
```
elif [ ! -d "./node_modules/" ]; then
    git submodule update --init --recursive
    npm ci --unsafe-perm
    ./docker/scripts/install-plugins.sh
fi
```

If you didn't install `node_modules` outside of Docker, it will enter this `elif` statement.
`git submodule update --init --recursive` crashes with message `fatal: not a git repository (or any of the parent directories)`.

This happens because the working directory of the Docker image is `/var/app` , and the current directory is mounted as a volume to `/app`. So we're not in the correct directory.

## Possible Solution
Either:
- change the image working directory to `/app`,
- change the container working directory to `/app`,
- mount the volume to `/var/app`.

I any case, I also wonder if it's the best idea to update submodules inside Docker, for two reasons:
- submodules are already initialised when git cloning the repo
- it can prevent reproducible builds, since it updates the submodules. And it updates them not only in Docker but also in the host, since it's mounted a volume.

To run it locally, I removed the `git submodule update --init --recursive` line (not necessary but I prefer it this way) and changed the container wd to `/app`.

## Steps to Reproduce
Fresh install, Kuzzle never ran on the machine using Docker and node modules are not installed:
```sh
git clone git@github.com:kuzzleio/kuzzle.git
cd kuzzle
docker-compose up
```

If you already ran Kuzzle locally:
```sh
# if you have other containers runner, you might want to target the containers/volumes you remove
docker stop $(docker ps -qa)
docker rm $(docker ps -qa)
docker volume prune
rm -rf node_modules 
```

## Context (Environment)
Kuzzle version: 79acecc28007e7f8b4b206cb655a0d1b97746100

Caused by https://github.com/kuzzleio/kuzzle/commit/c48fa76a6d1610baf99da5eec5b4e97fd1bbd06e#diff-4e5e90c6228fd48698d074241c2ba760R17

**Comment by Aschen** [comment] 2020-06-29 03:48
Hi @tsauvajon !

Thanks you for your feedback, I forget to revert this change on my last PR :expressionless: 
It's fixed now (I mount the application to the usual directory `var/app`)

>     submodules are already initialised when git cloning the repo

Maybe you have some special configuration because when I clone Kuzzle repository the submodules are empty

>     it can prevent reproducible builds, since it updates the submodules. And it updates them not only in Docker but also in the host, since it's mounted a volume.

I don't see why it can prevent reproducible build :thinking: It didn't really "updates" the subdomules but rather download them / upgrade them to the right commit

**Comment by tsauvajon** [comment] 2020-06-29 04:05
> Maybe you have some special configuration because when I clone Kuzzle repository the submodules are empty

Yes you're right, I've been using that config for so long I forgot it was not the default option

> I don't see why it can prevent reproducible build 🤔 It didn't really "updates" the subdomules but rather download them / upgrade them to the right commit

Correct, I got confused for a second. Submodule are set to fixed revisions, so it's a good idea to always update them. All good!

**Comment by scottinet** [comment] 2020-09-09 09:20
Fixed

**Closed by scottinet** 2020-09-09 09:20 UTC
Labels: bug
