### ISSUE TITLE
The request.context is not accessible in the plugin context

### ISSUE THREAD

**Issue by dbengsch** [kuzzleio/kuzzle#998] opened 2017-11-27 20:29 UTC
When trying to access the `request.context` from a plugin context, a core_dump is triggered.

**Comment by benoitvidis** [comment] 2017-12-04 13:40
@dbengsch, I cannot reproduce the issue.

### plugin

```js
class Test {
  constructor () {
    this.controllers = {
      test: {
        test: 'test'
      }
    };

    this.routes = [
      {verb: 'get', url: '/test', controller: 'test', action: 'test'}
    ];
  }

  init () {
  }

  test (request) {
    console.log(request.context.user._id);
    return Promise.resolve(request.context);
  }

}

module.exports = Test;
```

```
curl -H "Authorization: Bearer <JWT>" "http://localhost:7512/_plugin/test/test?pretty"
{
  "requestId": "05089f03-0ffe-4cd8-b449-f376ce30072e",
  "status": 200,
  "error": null,
  "controller": "test/test",
  "action": "test",
  "collection": null,
  "index": null,
  "volatile": null,
  "result": {
    "connectionId": "92d6c7a2-8c8a-4d20-a68f-eb735bc55a76",
    "protocol": "http",
    "user": {
      "_id": "admin",
      "profileIds": [
        "admin"
      ],
      "_kuzzle_info": {
        "author": "-1",
        "createdAt": 1512394341706,
        "updatedAt": null,
        "updater": null
      }
    },
    "token": {
      "_id": "<JWT>",
      "expiresAt": 1512398014293,
      "ttl": 3600000,
      "userId": "admin",
      "connectionId": null
    }
  }
}
```
(ok with anonymous too)

Can you provide some failing test scenario?

**Comment by benoitvidis** [comment] 2017-12-04 16:23
after discussion, closing the issue as non-reproducible.

**Closed by benoitvidis** 2017-12-04 16:23 UTC
Labels: bug, priority-high
